name: "Publish to npm"

run-name: "Publishing ${{ github.event.release.tag_name || 'manually' }} to npm"

on:
  release:
    types: [ "published" ]
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to npm"
        required: true
        type: "boolean"
        default: false

permissions:
  contents: "read"

env:
  PUBLISH: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.publish) }}
  WORKING_DIR: "${{ vars.NPM_WORKING_DIR }}"

jobs:
  publish-to-npm:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    permissions:
      id-token: "write"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v6"
        with:
          node-version-file: "${{ env.WORKING_DIR }}/package.json"
          package-manager-cache: false
          registry-url: "https://registry.npmjs.org"

      - name: "Remove deprecated .npmrc entries"
        run: |
          npmrc="${NPM_CONFIG_USERCONFIG:-$HOME/.npmrc}"

          if [ -f "$npmrc" ]; then
            sed -i '/^always-auth=/d' "$npmrc"
          fi
        working-directory: "${{ env.WORKING_DIR }}"

      - name: "Install packages"
        run: |
          npm install -g npm@latest
          npm install
        working-directory: "${{ env.WORKING_DIR }}"

      - name: "Build project"
        run: |
          npm run build
        working-directory: "${{ env.WORKING_DIR }}"

      - name: "Publish package to npm"
        run: |
          if [ "${PUBLISH}" = "true" ]; then
            echo "MODE: PRODUCTION"
            npm publish
          else
            echo "MODE: DRY RUN"
            npm publish --dry-run
          fi
        working-directory: "${{ env.WORKING_DIR }}"
