name: "Publish to GitHub Pages (Docusaurus)"

run-name: "Publishing ${{ github.event.release.tag_name }} to GitHub Pages"

on:
  release:
    types: [ "published" ]

permissions:
  contents: "read"
  id-token: "write"
  pages: "write"

jobs:
  publish-to-github-pages:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    env:
      WORKING_DIR: "${{ vars.DOCUSAURUS_WORKING_DIR }}"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v6"
        with:
          node-version-file: "${{ env.WORKING_DIR }}/package.json"
          package-manager-cache: false

      - name: "Update npm"
        run: "npm install -g npm@latest"
        working-directory: "${{ env.WORKING_DIR }}"

      - name: "Install packages"
        run: "npm install"
        working-directory: "${{ env.WORKING_DIR }}"

      - name: "Build project"
        run: "npm run build"
        working-directory: "${{ env.WORKING_DIR }}"

      - name: "Setup GitHub Pages"
        uses: "actions/configure-pages@v5"

      - name: "Upload artifact to GitHub Pages"
        uses: "actions/upload-pages-artifact@v4"
        with:
          path: "${{ env.WORKING_DIR }}/build"

      - name: "Deploy to GitHub Pages"
        uses: "actions/deploy-pages@v4"
